spring:
  profiles:
    active: local

webClient:
  requestTimeout: 1000
  readTimeout: 1000
  writeTimeout: 1000

youtube:
  playListItemPart: id, snippet
  playListItemUrl: https://www.googleapis.com/youtube/v3/playlistItems?key={key}&part={part}&playlistId={playlistId}&maxResults=10
  channelPart: id,snippet,brandingSettings,contentDetails,statistics
  channelUrl: https://www.googleapis.com/youtube/v3/channels?key={key}&part={part}&id={id}
  apiKey: ${API_KEY}

youtuberrenew:
  youTuberUpdateQuery: UPDATE you_tuber SET description = :description, channel_id = :channelId, published_at = :publishedAt,
    thumbnail = :thumbnail, country = :country, view_count = :viewCount, comment_count = :commentCount,
    subscriber_count = :subscriberCount, video_count = :videoCount, banner_img_url = :bannerImgUrl, play_list_id = :playListId
    WHERE id = :id

videorenew:
  playListInsertQuery: INSERT INTO video(you_tuber_id, published_at, thumbnail, youtube_video_id, title) VALUES(?, ?, ?, ?, ?)
  videoCountQuery: SELECT count(*) FROM video WHERE youtube_video_id = ?



ranking.step:
  numSelectQuery: SELECT num FROM check_ranking where category_id = ? and create_at = ?
  numInsertQuery: INSERT INTO check_ranking(num, category_id, create_at) VALUES(?, ?, ?)
  numUpdateQuery: UPDATE check_ranking SET num = ? where CREATE_AT = ?
  rankingInsertQuery: INSERT INTO ranking(name, ranking, create_at, view_count, subscriber_count, thumbnail, banner_img_url, category_id, you_tuber_id) VALUES(?, ?, ?, ? ,? ,? ,? ,? ,?)

logging.level.org.springframework.batch: DEBUG
spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  profiles: test
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
